global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # EasyRent MERN Stack (using container names)
  - job_name: 'easyrent-backend'
    static_configs:
      - targets: ['easyrent-backend:4001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'easyrent-nginx'
    static_configs:
      - targets: ['easyrent-nginx-exporter:9113']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # # Future Go API Services
  # - job_name: 'go-api'
  #   static_configs:
  #     - targets: ['host.docker.internal:8080']
  #   metrics_path: '/metrics'
  #   scrape_interval: 5s

  # - job_name: 'go-service-2'
  #   static_configs:
  #     - targets: ['host.docker.internal:8081']
  #   metrics_path: '/metrics'
  #   scrape_interval: 5s
